[package]
name = "rustbus_derive"
version = "0.1.0"
authors = ["Moritz Borcherding <moritz.borcherding@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
"rustbus" = {path = "../rustbus"}
syn = "1.0.44"
quote = "1.0.7"
proc-macro2 = "*"

