on: [push, pull_request]

name: CI

jobs:
  check:
      name: Check
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install stable toolchain
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: stable
            override: true

        - name: Run cargo check
          uses: actions-rs/cargo@v1
          with:
            command: check

  check-fuzz:
    name: Check fuzz builds
    runs-on: ubuntu-latest
    
    steps:
      - name: install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: install cargo-fuzz
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: -f cargo-fuzz

      - name: Run cargo fuzz build
        working-directory: rustbus
        run: cargo +nightly fuzz build

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # hits an ICE with clippy 0.0.212. There is a fix in their repo already so if version 0.0.213 comes out this should be reenabled
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  # fails CI because criterion needs two versions of autocfg
  #cargo-deny:
  #  name: Cargo Deny
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v1
  #  - uses: EmbarkStudios/cargo-deny-action@v0
